const EMPLOYEE_PERIOD_CHANGED = 'EMPLOYEE_PERIOD_CHANGED';
const EMPLOYEE_PERIOD_CHANGE_FROM_SERVER_SUCCESS = 'EMPLOYEE_PERIOD_CHANGE_FROM_SERVER_SUCCESS';
const EMPLOYEE_PERIOD_CHANGE_FROM_SERVER_FAILED = 'EMPLOYEE_PERIOD_CHANGE_FROM_SERVER_FAILED';
const LOGIN = 'LOGIN';

// could organize this better by section

export default {
  EMPLOYEE_PERIOD_CHANGED,
  EMPLOYEE_PERIOD_CHANGE_FROM_SERVER_FAILED,
  EMPLOYEE_PERIOD_CHANGE_FROM_SERVER_SUCCESS,
  LOGIN
};
