// could organize this better by section
export default {
  EMPLOYEE_PERIOD_CHANGED: 'EMPLOYEE_PERIOD_CHANGED',
  REMOTE_EMPLOYEE_PERIOD_CHANGE_FAILED: 'REMOTE_EMPLOYEE_PERIOD_CHANGE_FAILED',
  REMOTE_EMPLOYEE_PERIOD_CHANGE_SUCCESS: 'REMOTE_EMPLOYEE_PERIOD_CHANGE_SUCCESS',
  REMOTE_REVIEW_CONTENT_FAILED: 'REMOTE_REVIEW_CONTENT_FAILED',
  REMOTE_REVIEW_CONTENT_SUCCESS: 'REMOTE_REVIEW_CONTENT_SUCCESS',
  REMOTE_REVIEW_SUBMITTED_SUCCESS: 'REMOTE_REVIEW_SUBMITTED_SUCCESS',
  REMOTE_REVIEW_SUBMITTED_FAILED: 'REMOTE_REVIEW_SUBMITTED_FAILED',
  LOGIN: 'LOGIN',
  REVIEW_CLICKED_CREATE: 'REVIEW_CLICKED_CREATE',
  REVIEW_CLICKED_EDIT: 'REVIEW_CLICKED_EDIT',
  REVIEW_SUBMITTED: 'REVIEW_SUBMITTED'
}